### ISSUE TITLE
Uninstalling [...] Failed

### ISSUE THREAD

**Issue by anjeronett** [MechanicalDragon0687/TWLFix#5]
I don't know how to properly structure this, so here's what the text says:
"
Initializing APT services
Initializing AM services
Initializing PMT services

Press [A] to begin or [Start] to Exit!

Uninstalling System DSiWare:
Uninstalling 0004800f484e48441 Failed
Uninstalling 0004800f484c48441 Failed
Uninstalling 0004800542383841 Failed
Uninstalling 00048005484e4441 Failed
Uninstalling 0004013820000102 Failed

Done!
Reboot and then open System Update.

Press Start to reboot.
"
The New 3DS XL refuses to update.

**Comment by MechanicalDragon0687** [comment]
looks like those were already missing, the app cant remove apps that dont exist. seems there is another underlying issue with your being able to update. A Nand backup may be best
