### ISSUE TITLE
System does not update.

### ISSUE THREAD

**Issue by Jack06WS** [MechanicalDragon0687/TWLFix#6]
Hi there. I'm using this software on my Nintendo 2DS XL and I'm getting an issue with it. I'm using a DSiWare application that I paid for from the eShop, I've copied it to my SD card and put the 20000102.bin file along with it in the Nintendo DSiWare folder which I generated from https://3ds.nhnarwhal.com/3dstools/twlfix.php using my movable.sed file. When I reboot my console and go to the "Software Update" tab in my Settings application, it says that my console is "already up to date". I really don't know what else to do here, does anybody have any advice or tips to help me here? I'd really appreciate it.

DSiWare Application: Game & Watch Ball Nintendo
Device Firmware: 11.14.0-46E
Device Model: Nintendo 2DS XL

**Comment by MechanicalDragon0687** [comment]
sounds like you skipped opening data management->dsiware->sd and copying it to your system.
